#!/usr/bin/env ruby

require 'engine'

width, height, num_mines = 10, 20, 50
game = Engine::Minesweeper.new(width, height, num_mines)

while game.still_playing?
  valid_move = game.play(rand(width), rand(height))
  valid_flag = game.flag(rand(width), rand(height))
  if valid_move or valid_flag
    printer = (rand > 0.5) ? Engine::SimplePrinter.new : Engine::PrettyPrinter.new
    printer.print(game.board_state)
  end
end

puts 'Fim do jogo!'
if game.victory?
  puts 'Você venceu!'
else
  puts 'Você perdeu! As minas eram:'
  Engine::PrettyPrinter.new.print(game.board_state(xray: true))
end
